module.exports = function (sequelize, DataTypes){
    var PersonalInfo = sequelize.define("PersonalInfo",{
        name:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        last_Name:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        address:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        address2:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        city:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        state:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[2]
            }
        },
        zipCode:{
            type:DataTypes.INTEGER,
            allowNull:false,
            validate:{
                len:[5]
            }
        },
        phoneNumber:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[10]
            }
        },
        whPhoneNumber:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[10]
            }
        },
        dateOfBirth:{
            type:DataTypes.DATEONLY,
            allowNull:false,
            isDate:true,
        },
        sex:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        emergencyContactName:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        relationship:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[1]
            }
        },
        emergencyPhoneNumber:{
            type:DataTypes.STRING,
            allowNull:false,
            validate:{
                len:[10]
            }
        }
    });

    


    return PersonalInfo;


};